language: rust
rust:
  - 1.34.2
cache: cargo
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-deadlinks || echo "cargo-deadlinks already installed"
  - cargo install cargo-web || echo "cargo-web already installed"
script: ./check.sh