[package]
name = "egg"
version = "0.1.2"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"
description = "An implementation of egraphs"
repository = "https://github.com/mwillsey/egg"
readme = "README.md"
license = "MIT"
keywords = ["e-graphs"]
categories = ["data-structures"]

[dependencies]
symbolic_expressions = "5"
log = "0.4"
itertools = "0.8"
smallvec = "1"
indexmap = "1"
instant = "0.1"
# for the serde-1 feature
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
env_logger = "0.7"
ordered-float = "1"

[features]
parent-pointers = []
stdweb = [ "instant/stdweb" ]
serde-1 = [ "serde", "indexmap/serde-1" ]

[workspace]
members = [
    ".",
    "web-demo",
]

[profile.test]
debug = true
opt-level = 1

[profile.release]
debug = true
