[package]
name = "ears"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.0"
log = "0.4.0"

[dev-dependencies]
env_logger = "0.6.1"
maplit = "1"
strum = "0.15"
strum_macros = "0.15"

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.16.3"