[package]
name = "web-demo"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"


[dependencies]
stdweb = "0.4.17"
yew = "0.6"

egg = { path = "../egg" }

log = "0.4"

strum = "0.15"
strum_macros = "0.15"
ordered-float = "1"
